### ISSUE TITLE
Change -V flag in mkiso as it may be confused with -v

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/tools#8]
mkiso in its development branch, has two flags `-V` and `-v` which utilize the same letter.

https://github.com/Nitrux/tools/blob/664fe630d701d70ed8a83f434cba479ccc7400b3/mkiso#L15

I suggest using `-l` or `-L` for `label` instead to avoid confusion.

**Comment by lslvr** [comment]
Solved. The new flag is `-r`.
